### ISSUE TITLE
`onSearchBoxClosed` not triggering when searchbox is closed

### ISSUE THREAD

**Issue by DorianWilhelm** [oramasearch/orama-ui-components#60]
Hi,

The [docs](https://docs.orama.com/cloud/ui-components/search-box) don't state any method for managing the `open` state when the `SearchBox` gets closed but I've found the prop `onSearchBoxClosed` being used in other [PRs](https://github.com/TanStack/tanstack.com/commit/ed443344d0553681dde5867c24ec42ae8f7df280#diff-4841df9ba23b7864070f439e06f4231f4731424a3676c9ea5933b582bfd7db35R559)

However it does not trigger when closing the modal by hitting escape or clicking outside.
It seems the modal always stays open and is just being hidden via `display: "hidden"`.
This has the unfortunate effect of reopening the modal when some prop updates on the `SearchBox` like the `colorScheme`.

Here's a codesandbox that showcases the issue:
https://codesandbox.io/p/devbox/27gz99

Thanks so much for the effort ❤️

**Comment by g-francesca** [comment]
Hey @DorianWilhelm, 
I was reviewing the sandbox you shared, and based on the current implementation, you don't actually need to set an `open` variable. The modal's open and close states are managed automatically.

We are planning to make some improvements to allow you to run custom callback functions when the search box closes, but this feature is not supported at the moment.

Thank you for highlighting this. We are also working to make the documentation clearer, and your feedback is greatly appreciated! 💕 

Let me know if you need some more help. Thank you

**Comment by DorianWilhelm** [comment]
Aah I see, yes the docs could be clearer regarding that.
Thank you, works as expected 👌
